<a href="https://colab.research.google.com/github/Owee-Angare/Robo/blob/master/Predicting_Robot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf 
import tensorflow.keras as keras 
import numpy as np 
import pandas as pd
df=pd.read_csv('RobotConversationcsv.csv')  
df 

num1  num2  num3  num4  num5  num6  num7  num8  num9  num10  source
0          2     5     2     5     6     2     1     8     1      3       0
1          4     9     5     4     8     6     6     7     7      2       0
2          1     6     5     8     8     8     2     6     9      6       0
3          7     5     3     3     8     9     8     6     7      2       0
4          3     7     9     2     5     8     8     7     5      4       0
...      ...   ...   ...   ...   ...   ...   ...   ...   ...    ...     ...
199994  6994  7003  7006  7010  7013  7014  7019  7026  7030   7038       1
199995  2495  2503  2509  2512  2513  2517  2521  2526  2528   2533       1
199996  7353  7357  7364  7366  7374  7380  7382  7384  7388   7391       1
199997  8905  8911  8913  8920  8924  8925  8928  8936  8943   8947       1
199998  4882  4886  4888  4896  4902  4903  4907  4912  4920   4924       1

[199999 rows x 11 columns]

In [3]:
#Input and Output 
x=df.iloc[:,0:10].values
y=df.iloc[:,10].values 
y 

array([0, 0, 0, ..., 1, 1, 1])

In [4]:
#Defining Keras model with 2 hidden layers and 1 outut layer
model=tf.keras.Sequential()
model.add(keras.layers.Dense(12,input_dim=10,activation='relu'))
model.add(keras.layers.Dense(8,activation='relu'))
model.add(keras.layers.Dense(1,activation='sigmoid')) 

In [5]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy']) 

In [6]:
model.fit(x,y,epochs=50) 

Epoch 1/50
6250/6250 [==============================] - 9s 1ms/step - loss: 0.0188 - accuracy: 0.9947
Epoch 2/50
6250/6250 [==============================] - 9s 1ms/step - loss: 7.1490e-05 - accuracy: 1.0000
Epoch 3/50
6250/6250 [==============================] - 9s 1ms/step - loss: 9.1058e-06 - accuracy: 1.0000
Epoch 4/50
6250/6250 [==============================] - 9s 1ms/step - loss: 0.0056 - accuracy: 0.9999
Epoch 5/50
6250/6250 [==============================] - 9s 1ms/step - loss: 1.8825e-06 - accuracy: 1.0000
Epoch 6/50
6250/6250 [==============================] - 9s 1ms/step - loss: 4.6428e-07 - accuracy: 1.0000
Epoch 7/50
6250/6250 [==============================] - 9s 1ms/step - loss: 2.9114e-08 - accuracy: 1.0000
Epoch 8/50
6250/6250 [==============================] - 9s 1ms/step - loss: 6.8622e-09 - accuracy: 1.0000
Epoch 9/50
6250/6250 [==============================] - 9s 1ms/step - loss: 1.8973e-08 - accuracy: 1.0000
Epoch 10/50
6250/6250 [==============================]

In [7]:
predictions=model.predict_classes(x)
predictions  

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]], dtype=int32)

In [9]:
from sklearn.metrics import confusion_matrix 
confusion_matrix (y,predictions)   

array([[100000,      0],
       [     0,  99999]])