<a href="https://colab.research.google.com/github/Owee-Angare/Robo/blob/master/Robot_Conversation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import tensorflow as tf 
import tensorflow.keras as keras 
import numpy as np 
import pandas as pd
df=pd.read_csv('RobotConversation.csv')  
df 

num1    num2     num3  ...          num9         num10  source
0         2       5        2  ...  1.000000e+00  3.000000e+00       0
1      1747    1749     1751  ...  1.783000e+03  1.785000e+03       1
2     65056  195168  1561344  ...  6.745006e+09  6.745006e+09       2
3      2855    2860     2865  ...  2.895000e+03  2.900000e+03       3
4     11440   57200   286000  ...  4.468750e+09  2.234375e+10       4
...     ...     ...      ...  ...           ...           ...     ...
4444  33060  165300   826500  ...  1.291406e+10  6.457031e+10       4
4445      3       5        1  ...  2.000000e+00  4.000000e+00       0
4446   2071    2073     2081  ...  2.115000e+03  2.118000e+03       1
4447  35540  284320   568640  ...  2.388288e+09  1.910630e+10       2
4448   1962    1967     1972  ...  2.002000e+03  2.007000e+03       3

[4449 rows x 11 columns]

In [7]:
#Input and Output 
x=df.iloc[:,0:10].values
y=df.iloc[:,10].values 
y 

array([0, 1, 2, ..., 1, 2, 3])

In [8]:
#Defining Keras model with 2 hidden layers and 1 outut layer
model=tf.keras.Sequential()
model.add(keras.layers.Dense(12,input_dim=10,activation='relu'))
model.add(keras.layers.Dense(8,activation='relu'))
model.add(keras.layers.Dense(5,activation='softmax')) 

In [9]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy']) 

In [10]:
model.fit(x,y,epochs=50) 

Epoch 1/50
140/140 [==============================] - 0s 1ms/step - loss: 89953000.0000 - accuracy: 0.3940
Epoch 2/50
140/140 [==============================] - 0s 1ms/step - loss: 39336744.0000 - accuracy: 0.3949
Epoch 3/50
140/140 [==============================] - 0s 1ms/step - loss: 13697742.0000 - accuracy: 0.4608
Epoch 4/50
140/140 [==============================] - 0s 1ms/step - loss: 39892648.0000 - accuracy: 0.4630
Epoch 5/50
140/140 [==============================] - 0s 1ms/step - loss: 32968468.0000 - accuracy: 0.4799
Epoch 6/50
140/140 [==============================] - 0s 1ms/step - loss: 7010180.0000 - accuracy: 0.5808
Epoch 7/50
140/140 [==============================] - 0s 1ms/step - loss: 4206258.5000 - accuracy: 0.6395
Epoch 8/50
140/140 [==============================] - 0s 1ms/step - loss: 1386428.3750 - accuracy: 0.6858
Epoch 9/50
140/140 [==============================] - 0s 1ms/step - loss: 3591291.2500 - accuracy: 0.6945
Epoch 10/50
140/140 [====================

In [11]:
predictions=model.predict_classes(x)
predictions 

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([0, 3, 2, ..., 1, 2, 3])

In [12]:
y 

array([0, 1, 2, ..., 1, 2, 3])

In [13]:
from sklearn.metrics import confusion_matrix 
confusion_matrix (y,predictions) 

array([[890,   0,   0,   0,   0],
       [  0, 696,  15, 179,   0],
       [  0,   0, 880,   0,  10],
       [  0, 711,   9, 170,   0],
       [  0,   0, 889,   0,   0]])